name: application_busca_cep
description: Aplicativo buscar Cep.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  connectivity_plus: ^3.0.3
  font_awesome_flutter: ^10.3.0
  animated_text_kit: ^4.2.2
  mask_text_input_formatter: ^2.5.0
  #OBJECT BOX
  objectbox: ^2.1.0
  objectbox_flutter_libs: ^2.1.0
  path_provider: ^2.1.0
  http: ^0.13.5
  modal_bottom_sheet: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #OBJECT_BOX
  build_runner: ^2.0.0
  objectbox_generator: any
  # objectbox_generator:

  flutter_lints: ^2.0.0


objectbox:
  output_dir: src/database

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/video/